server:
  port: 8081

spring:
  application:
    name: servico-produtos
  datasource:
    url: jdbc:postgresql://localhost:5432/microsservicos_db?currentSchema=produtos_schema
    username: admin
    password: admin_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: produtos
        hbm2ddl.create_namespaces: true
